import type { ComponentSchema } from '../types';

const UI = '@truongdq01/ui' as const;

const nativeOnly = (
  schema: Omit<ComponentSchema, 'support'> & {
    supportReason: string;
    webPreview?: boolean;
  }
): ComponentSchema => ({
  ...schema,
  support: {
    native: true,
    webPreview: schema.webPreview ?? false,
    reason: schema.supportReason,
  },
});

export const nativeOnlyComponentSchemas: ComponentSchema[] = [
  nativeOnly({
    name: 'Modal',
    package: UI,
    category: 'overlay',
    status: 'stable',
    description: 'Native modal overlay with compound header/content/footer.',
    supportReason:
      'Depends on native Modal, AnimatedOverlay, and safe-area behavior',
    import: { named: 'Modal', from: UI, lazyKey: 'Modal' },
    props: [],
    examples: [],
    docsPath: 'components/modal',
    avoid: ['Not available in web preview MVP'],
  }),
  nativeOnly({
    name: 'Dialog',
    package: UI,
    category: 'overlay',
    status: 'stable',
    description: 'Decision surface with title, content, and actions.',
    supportReason: 'Portal/overlay behavior and native presentation',
    import: { named: 'Dialog', from: UI, lazyKey: 'Dialog' },
    props: [],
    examples: [],
    docsPath: 'components/dialog',
  }),
  nativeOnly({
    name: 'AlertDialog',
    package: UI,
    category: 'overlay',
    status: 'stable',
    description: 'Critical confirmation dialog.',
    supportReason: 'Built on Dialog native overlay stack',
    import: { named: 'AlertDialog', from: UI, lazyKey: 'AlertDialog' },
    props: [],
    examples: [],
    docsPath: 'components/alert-dialog',
  }),
  nativeOnly({
    name: 'BottomSheet',
    package: UI,
    category: 'overlay',
    status: 'beta',
    description: 'Gesture-driven sheet with snap points.',
    supportReason: 'Requires Reanimated gestures and native sheet physics',
    import: { named: 'BottomSheet', from: UI, lazyKey: 'BottomSheet' },
    props: [],
    examples: [],
    docsPath: 'components/bottom-sheet',
  }),
  nativeOnly({
    name: 'DatePicker',
    package: UI,
    category: 'data-entry',
    status: 'beta',
    description: 'Native date/time picker.',
    supportReason: 'Uses @react-native-community/datetimepicker native module',
    import: { named: 'DatePicker', from: UI, lazyKey: 'DatePicker' },
    props: [],
    examples: [],
    docsPath: 'components/date-picker',
  }),
  nativeOnly({
    name: 'Drawer',
    package: UI,
    category: 'overlay',
    status: 'beta',
    description: 'Side drawer panel with gesture dismiss.',
    supportReason: 'Gesture + Reanimated panel animation',
    import: { named: 'Drawer', from: UI, lazyKey: 'Drawer' },
    props: [],
    examples: [],
    docsPath: 'components/drawer',
  }),
  nativeOnly({
    name: 'Popover',
    package: UI,
    category: 'overlay',
    status: 'beta',
    description: 'Anchored floating content.',
    supportReason: 'Measure/layout anchoring differs on web vs native',
    import: { named: 'Popover', from: UI, lazyKey: 'Popover' },
    props: [],
    examples: [],
    docsPath: 'components/popover',
  }),
  nativeOnly({
    name: 'Popper',
    package: UI,
    category: 'overlay',
    status: 'experimental',
    description: 'Positioned overlay relative to anchor.',
    supportReason: 'Native measure and portal positioning',
    import: { named: 'Popper', from: UI, lazyKey: 'Popper' },
    props: [],
    examples: [],
    docsPath: 'components/popper',
  }),
  nativeOnly({
    name: 'ContextMenu',
    package: UI,
    category: 'overlay',
    status: 'beta',
    description: 'Long-press context menu.',
    supportReason: 'Native context menu / gesture coordination',
    import: { named: 'ContextMenu', from: UI, lazyKey: 'ContextMenu' },
    props: [],
    examples: [],
    docsPath: 'components/context-menu',
  }),
  nativeOnly({
    name: 'Carousel',
    package: UI,
    category: 'data-display',
    status: 'beta',
    description: 'Swipeable carousel with pagination.',
    supportReason: 'Gesture handler and Reanimated paging',
    import: { named: 'Carousel', from: UI, lazyKey: 'Carousel' },
    props: [],
    examples: [],
    docsPath: 'components/carousel',
  }),
  nativeOnly({
    name: 'AnimatedOverlay',
    package: UI,
    category: 'overlay',
    status: 'beta',
    description: 'Animated backdrop wrapper for overlays.',
    supportReason: 'Reanimated enter/exit and native modal host',
    import: { named: 'AnimatedOverlay', from: UI, lazyKey: 'AnimatedOverlay' },
    props: [],
    examples: [],
    docsPath: 'components/animated-overlay',
  }),
  nativeOnly({
    name: 'AnimatedList',
    package: UI,
    category: 'data-display',
    status: 'experimental',
    description: 'List with layout animations.',
    supportReason: 'Reanimated layout animations and list virtualization',
    import: { named: 'AnimatedList', from: UI, lazyKey: 'AnimatedList' },
    props: [],
    examples: [],
    docsPath: 'components/animated-list',
  }),
  nativeOnly({
    name: 'Toast',
    package: UI,
    category: 'feedback',
    status: 'stable',
    description: 'Transient toast notification host.',
    supportReason: 'Portal positioning and native toast host',
    import: { named: 'Toast', from: UI, lazyKey: 'Toast' },
    props: [],
    examples: [],
    docsPath: 'components/toast',
  }),
  nativeOnly({
    name: 'Snackbar',
    package: UI,
    category: 'feedback',
    status: 'stable',
    description: 'Bottom snackbar message.',
    supportReason: 'Native positioning and safe-area insets',
    import: { named: 'Snackbar', from: UI, lazyKey: 'Snackbar' },
    props: [],
    examples: [],
    docsPath: 'components/snackbar',
  }),
  nativeOnly({
    name: 'Tabs',
    package: UI,
    category: 'navigation',
    status: 'beta',
    description: 'Tabbed navigation with animated indicator.',
    supportReason: 'Reanimated indicator and gesture-heavy tab bar',
    import: { named: 'Tabs', from: UI, lazyKey: 'Tabs' },
    props: [],
    examples: [],
    docsPath: 'components/tabs',
  }),
  nativeOnly({
    name: 'Select',
    package: UI,
    category: 'forms',
    status: 'beta',
    description: 'Dropdown select with sheet/modal presentation.',
    supportReason: 'Native sheet/modal picker and gesture interactions',
    import: { named: 'Select', from: UI, lazyKey: 'Select' },
    props: [],
    examples: [],
    docsPath: 'components/select',
  }),
];
