import type { ComponentSchema } from '../types';

/** Import specifier for a registry kit component: `@/components/ui/<kebab>`. */
const uiImport = (named: string, file: string, lazyKey = named) =>
  ({ named, from: `@/components/ui/${file}`, lazyKey }) as const;

const nativeOnly = (
  schema: Omit<ComponentSchema, 'support'> & {
    supportReason: string;
    webPreview?: boolean;
  }
): ComponentSchema => ({
  ...schema,
  support: {
    native: true,
    webPreview: schema.webPreview ?? false,
    reason: schema.supportReason,
  },
});

export const nativeOnlyComponentSchemas: ComponentSchema[] = [
  nativeOnly({
    name: 'Modal',
    category: 'overlay',
    status: 'stable',
    description: 'Native modal overlay with compound header/content/footer.',
    supportReason:
      'Depends on native Modal, AnimatedOverlay, and safe-area behavior',
    import: uiImport('Modal', 'modal'),
    props: [],
    examples: [],
    docsPath: 'components/modal',
    avoid: ['Not available in web preview MVP'],
  }),
  nativeOnly({
    name: 'Dialog',
    category: 'overlay',
    status: 'stable',
    description: 'Decision surface with title, content, and actions.',
    supportReason: 'Portal/overlay behavior and native presentation',
    import: uiImport('Dialog', 'dialog'),
    props: [],
    examples: [],
    docsPath: 'components/dialog',
  }),
  nativeOnly({
    name: 'AlertDialog',
    category: 'overlay',
    status: 'stable',
    description: 'Critical confirmation dialog.',
    supportReason: 'Built on Dialog native overlay stack',
    import: uiImport('AlertDialog', 'alert-dialog'),
    props: [],
    examples: [],
    docsPath: 'components/alert-dialog',
  }),
  nativeOnly({
    name: 'Sheet',
    category: 'overlay',
    status: 'beta',
    description: 'Gesture-driven bottom sheet with snap points.',
    supportReason: 'Requires Reanimated gestures and native sheet physics',
    import: uiImport('Sheet', 'sheet'),
    props: [],
    examples: [],
    docsPath: 'components/sheet',
  }),
  nativeOnly({
    name: 'DatePicker',
    category: 'data-entry',
    status: 'beta',
    description: 'Native date/time picker.',
    supportReason: 'Uses @react-native-community/datetimepicker native module',
    import: uiImport('DatePicker', 'date-picker'),
    props: [],
    examples: [],
    docsPath: 'components/date-picker',
  }),
  nativeOnly({
    name: 'Drawer',
    category: 'overlay',
    status: 'beta',
    description: 'Side drawer panel with gesture dismiss.',
    supportReason: 'Gesture + Reanimated panel animation',
    import: uiImport('Drawer', 'drawer'),
    props: [],
    examples: [],
    docsPath: 'components/drawer',
  }),
  nativeOnly({
    name: 'Popover',
    category: 'overlay',
    status: 'beta',
    description: 'Anchored floating content.',
    supportReason: 'Measure/layout anchoring differs on web vs native',
    import: uiImport('Popover', 'popover'),
    props: [],
    examples: [],
    docsPath: 'components/popover',
  }),
  nativeOnly({
    name: 'Popper',
    category: 'overlay',
    status: 'experimental',
    description: 'Positioned overlay relative to anchor.',
    supportReason: 'Native measure and portal positioning',
    import: uiImport('Popper', 'popper'),
    props: [],
    examples: [],
    docsPath: 'components/popper',
  }),
  nativeOnly({
    name: 'ContextMenu',
    category: 'overlay',
    status: 'beta',
    description: 'Long-press context menu.',
    supportReason: 'Native context menu / gesture coordination',
    import: uiImport('ContextMenu', 'context-menu'),
    props: [],
    examples: [],
    docsPath: 'components/context-menu',
  }),
  nativeOnly({
    name: 'DropdownMenu',
    category: 'overlay',
    status: 'beta',
    description:
      'Anchored dropdown menu with trigger/content/item compound API.',
    supportReason: 'Anchored overlay positioning and trigger measurement',
    import: uiImport('DropdownMenu', 'dropdown-menu'),
    props: [],
    examples: [],
    docsPath: 'components/dropdown-menu',
  }),
  nativeOnly({
    name: 'Carousel',
    category: 'data-display',
    status: 'beta',
    description: 'Swipeable carousel with pagination.',
    supportReason: 'Gesture handler and Reanimated paging',
    import: uiImport('Carousel', 'carousel'),
    props: [],
    examples: [],
    docsPath: 'components/carousel',
  }),
  nativeOnly({
    name: 'AnimatedOverlay',
    category: 'overlay',
    status: 'beta',
    description: 'Animated backdrop wrapper for overlays.',
    supportReason: 'Reanimated enter/exit and native modal host',
    import: uiImport('AnimatedOverlay', 'animated-overlay'),
    props: [],
    examples: [],
    docsPath: 'components/animated-overlay',
  }),
  nativeOnly({
    name: 'AnimatedList',
    category: 'data-display',
    status: 'experimental',
    description: 'List with layout animations.',
    supportReason: 'Reanimated layout animations and list virtualization',
    import: uiImport('AnimatedList', 'animated-list'),
    props: [],
    examples: [],
    docsPath: 'components/animated-list',
  }),
  nativeOnly({
    name: 'Toast',
    category: 'feedback',
    status: 'stable',
    description: 'Transient toast notification host.',
    supportReason: 'Portal positioning and native toast host',
    import: uiImport('Toast', 'toast'),
    props: [],
    examples: [],
    docsPath: 'components/toast',
  }),
  nativeOnly({
    name: 'Snackbar',
    category: 'feedback',
    status: 'stable',
    description: 'Bottom snackbar message.',
    supportReason: 'Native positioning and safe-area insets',
    import: uiImport('Snackbar', 'snackbar'),
    props: [],
    examples: [],
    docsPath: 'components/snackbar',
  }),
  nativeOnly({
    name: 'Tabs',
    category: 'navigation',
    status: 'beta',
    description: 'Tabbed navigation with animated indicator.',
    supportReason: 'Reanimated indicator and gesture-heavy tab bar',
    import: uiImport('Tabs', 'tabs'),
    props: [],
    examples: [],
    docsPath: 'components/tabs',
  }),
  nativeOnly({
    name: 'Select',
    category: 'forms',
    status: 'beta',
    description: 'Dropdown select with sheet/modal presentation.',
    supportReason: 'Native sheet/modal picker and gesture interactions',
    import: uiImport('Select', 'select'),
    props: [],
    examples: [],
    docsPath: 'components/select',
  }),
];
