import * as components from './components';
import type { SemanticTokens } from './semantic';

export function resolveComponentTokens(t: SemanticTokens) {
  return {
    button: components.buttonTokens(t),
    input: components.inputTokens(t),
    card: components.cardTokens(t),
    badge: components.badgeTokens(t),
    toast: components.toastTokens(t),
    avatar: components.avatarTokens(t),
    checkbox: components.checkboxTokens(t),
    switch: components.switchTokens(t),
    radio: components.radioTokens(t),
    slider: components.sliderTokens(t),
    chip: components.chipTokens(t),
    fab: components.fabTokens(t),
    dialog: components.dialogTokens(t),
    tabs: components.tabsTokens(t),
    select: components.selectTokens(t),
    rating: components.ratingTokens(t),
    pagination: components.paginationTokens(t),
    timeline: components.timelineTokens(t),
    accordion: components.accordionTokens(t),
    alert: components.alertTokens(t),
    carousel: components.carouselTokens(t),
    animatedList: components.animatedListTokens(t),
    appBar: components.appBarTokens(t),
    autocomplete: components.autocompleteTokens(t),
    bottomNavigation: components.bottomNavigationTokens(t),
    bottomSheet: components.bottomSheetTokens(t),
    box: components.boxTokens(t),
    breadcrumbs: components.breadcrumbsTokens(t),
    buttonGroup: components.buttonGroupTokens(t),
    circularProgress: components.circularProgressTokens(t),
    datePicker: components.datePickerTokens(t),
    divider: components.dividerTokens(t),
    drawer: components.drawerTokens(t),
    emptyState: components.emptyStateTokens(t),
    formControl: components.formControlTokens(t),
    formField: components.formFieldTokens(t),
    formGroup: components.formGroupTokens(t),
    grid: components.gridTokens(t),
    icon: components.iconTokens(t),
    image: components.imageTokens(t),
    imageList: components.imageListTokens(t),
    linearProgress: components.linearProgressTokens(t),
    link: components.linkTokens(t),
    list: components.listTokens(t),
    menu: components.menuTokens(t),
    modal: components.modalTokens(t),
    otpInput: components.otpInputTokens(t),
    paper: components.paperTokens(t),
    popover: components.popoverTokens(t),
    popper: components.popperTokens(t),
    pressable: components.pressableTokens(t),
    segmentedControl: components.segmentedControlTokens(t),
    skeleton: components.skeletonTokens(t),
    snackbar: components.snackbarTokens(t),
    speedDial: components.speedDialTokens(t),
    stack: components.stackTokens(t),
    stepper: components.stepperTokens(t),
    table: components.tableTokens(t),
    textArea: components.textAreaTokens(t),
    textField: components.textFieldTokens(t),
    toggleButton: components.toggleButtonTokens(t),
    tooltip: components.tooltipTokens(t),
    typography: components.typographyTokens(t),
  } as const;
}

export type ComponentTokens = ReturnType<typeof resolveComponentTokens>;

// Re-export individual tokens for library consumers if needed
export * from './components';
