export const COUNTRIES = [
  { label: 'Việt Nam', value: 'vn' },
  { label: 'Japan', value: 'jp' },
  { label: 'Singapore', value: 'sg' },
  { label: 'South Korea', value: 'kr' },
];

export const LARGE_COUNTRIES = Array.from({ length: 50 }, (_, i) => ({
  label: `Country ${i + 1}`,
  value: `c${i}`,
}));

export const CONTACTS = [
  {
    id: '1',
    name: 'An Nguyen',
    role: 'Designer',
    initials: 'AN',
    time: '15:52',
    unread: 0,
  },
  {
    id: '2',
    name: 'Binh Tran',
    role: 'You: Sounds good',
    initials: 'BT',
    time: 'T.4',
    unread: 3,
  },
  {
    id: '3',
    name: 'Chi Le',
    role: 'Product sync tomorrow',
    initials: 'CL',
    time: '27/03',
    unread: 0,
  },
  {
    id: '4',
    name: 'Duy Pham',
    role: 'Developer',
    initials: 'DP',
    time: '12:00',
    unread: 1,
  },
  {
    id: '5',
    name: 'Elena Nguyen',
    role: 'Product Manager',
    initials: 'EN',
    time: 'Yesterday',
    unread: 0,
  },
  {
    id: '6',
    name: 'Fiona Tran',
    role: 'Marketing',
    initials: 'FT',
    time: 'Monday',
    unread: 0,
  },
  {
    id: '7',
    name: 'Gia Bao',
    role: 'QA Engineer',
    initials: 'GB',
    time: '20/03',
    unread: 2,
  },
  {
    id: '8',
    name: 'Hoang Nam',
    role: 'DevOps',
    initials: 'HN',
    time: '18/03',
    unread: 0,
  },
  {
    id: '9',
    name: 'Iris Le',
    role: 'Content Creator',
    initials: 'IL',
    time: '15/03',
    unread: 5,
  },
  {
    id: '10',
    name: 'Khanh Doan',
    role: 'Backend Developer',
    initials: 'KD',
    time: '14/03',
    unread: 0,
  },
  {
    id: '11',
    name: 'Lan Anh',
    role: 'Frontend Developer',
    initials: 'LA',
    time: '12/03',
    unread: 1,
  },
  {
    id: '12',
    name: 'Minh Quan',
    role: 'Mobile Lead',
    initials: 'MQ',
    time: '10/03',
    unread: 0,
  },
  {
    id: '13',
    name: 'Ngoc Trinh',
    role: 'Influencer',
    initials: 'NT',
    time: '08/03',
    unread: 10,
  },
  {
    id: '14',
    name: 'Phuong Vy',
    role: 'Copywriter',
    initials: 'PV',
    time: '05/03',
    unread: 0,
  },
  {
    id: '15',
    name: 'Quoc Anh',
    role: 'Data Scientist',
    initials: 'QA',
    time: '02/03',
    unread: 2,
  },
  {
    id: '16',
    name: 'Son Tung',
    role: 'Artist',
    initials: 'ST',
    time: '01/03',
    unread: 0,
  },
  {
    id: '17',
    name: 'Thuy Tien',
    role: 'Volunteer',
    initials: 'TT',
    time: '28/02',
    unread: 0,
  },
  {
    id: '18',
    name: 'Uyen Nhi',
    role: 'Customer Support',
    initials: 'UN',
    time: '25/02',
    unread: 3,
  },
  {
    id: '19',
    name: 'Viet Hoang',
    role: 'Project Lead',
    initials: 'VH',
    time: '22/02',
    unread: 0,
  },
] as any;

export type Contact = (typeof CONTACTS)[number];

export type MainTab = 'components' | 'data' | 'feedback' | 'settings';
