/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import "@storybook/addon-ondevice-controls/register";

type RequireContext = (path: string, recursive: boolean, pattern: RegExp) => unknown;
type RequireWithContext = NodeRequire & { context: RequireContext };

declare const module: { hot?: { accept?: () => void } } | undefined;

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./stories",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    req: (require as RequireWithContext).context(
      '../stories',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET: { host: string; port: number } | undefined;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

globalThis.STORIES = normalizedStories;


(module as { hot?: { accept?: () => void } } | undefined)?.hot?.accept?.();



if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,

  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
