import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['getting-started', 'theming', 'headless', 'component-tree'],
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        title: 'UI Components',
        description:
          'A comprehensive collection of 62+ React Native UI components.',
        slug: '/components',
      },
      items: [{ type: 'autogenerated', dirName: 'components' }],
    },
  ],
};

export default sidebars;
