import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: ["getting-started", "theming", "headless"],
    },
    {
      type: "category",
      label: "Components",
      items: [
        "components/button",
        "components/button-group",
        "components/fab",
        "components/text-field",
        "components/input",
        "components/password-input",
        "components/text-area",
        "components/select",
        "components/autocomplete",
        "components/checkbox",
        "components/radio-group",
        "components/switch",
        "components/slider",
        "components/rating",
        "components/toggle-button",
        "components/box",
        "components/stack",
        "components/grid",
        "components/app-bar",
        "components/tabs",
        "components/drawer",
        "components/menu",
        "components/stepper",
        "components/pagination",
        "components/bottom-navigation",
        "components/breadcrumbs",
        "components/speed-dial",
        "components/link",
        "components/paper",
        "components/card",
        "components/accordion",
        "components/typography",
        "components/table",
        "components/list",
        "components/chip",
        "components/avatar",
        "components/badge",
        "components/tooltip",
        "components/divider",
        "components/image-list",
        "components/timeline",
        "components/icon",
        "components/alert",
        "components/dialog",
        "components/snackbar",
        "components/circular-progress",
        "components/linear-progress",
        "components/skeleton",
        "components/toast",
        "components/empty-state",
        "components/modal",
        "components/popover",
        "components/popper",
        "components/form-control",
        "components/form-field",
        "components/pressable",
        "components/bottom-sheet",
      ],
    },
  ],
};

export default sidebars;
